service:
  targetPort: 3000

env:
  PORT: 3000
  SNOOTY_DB_NAME: docs_chat_prod

envSecrets:
  ATLAS_URI: chat-server-atlas-uri-prod

ingress:
  enabled: true
  hosts:
    - chat-server.docs.prod.corp.mongodb.com

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
